### ISSUE TITLE
Cannot integrate with private repositories

### ISSUE THREAD

**Issue by lukasburda** [jboss/tyr#157]
Private repositories need authorization token in parameters when performing communication with GitHub API.

error: https://pastebin.com/Xsh5BDeW

**Comment by xvanick1** [comment]
I have successfully reproduced your problem and investigated the code. I have tracked the problem to the request builder in the getJSONReader(uri) method in the GitHubService.java where it seem to occur and I tried to check if there have to be any differences on how to build the request for the public vs private repository. I came to conclusion that the request header does not need any extra content when integrating for the private repository.

After that, I have checked the scope of the personal access token for tyr and it seems like that if you want to have the current version of tyr integrated with a public repository, the current scope **"repo:status - Access commit status"** is enough, but when integrating with private repository, the scope have to be extended to **"repo - Full control of private repositories"** otherwise github will refuse the access. 

There is written the following in the [github docs](https://docs.github.com/en/developers/apps/scopes-for-oauth-apps#available-scopes) for the scope **"repo:status"** : 
>_Grants read/write access to public and private repository commit statuses. This scope is only necessary to grant other users or services access to private repository commit statuses without granting access to the code._

Therefore using scope **"repo:status"** of the access token should be enough also for the private repositories, but as the tyr is working with more than just commit statuses, we are forced to extend it's permissions.
